### ISSUE TITLE
August planning

### ISSUE THREAD

**Issue by pkantue** [pkantue/molomolotech#15]
This is the episode planning for the month of August:
- [x]  Edit and publish Queen Ndlovu episode. #17 
- [ ]  Dev, shoot, episode on Impostor Syndrome (mindset). #22 
- [ ] Podcast on why on the importance of coaching #23 
- [ ] Explainer video on coachee types

**Comment by pkantue** [comment]
This is no longer required. task to be closed.
